baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

paginate = 2

[params]
description = "The fastest blog website ever."
dateFormat = "Jan 2, 2006"


[taxonomies]
category = "categories"
author = "authors"